theme: jekyll-theme-hacker
title: Cooper's ePortfolio
description: This portfolio shows two projects I built in earlier courses and then enhanced. For each one, I explain what the project does, how I improved it, and include code highlights.
